{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.forgestove.gradle",
    "module": "ModAccessor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModAccessor-1.0.0.jar",
          "url": "ModAccessor-1.0.0.jar",
          "size": 35952699,
          "sha512": "ab48c13bab732d84702e178e143689ef5c626e56cac9221f01c863b7254dadf151e727cfbb676c9984e17a18e391f5ac42e4fd2a065840d9ebede87708647321",
          "sha256": "c6e718771b94918a991d8cb7bb13dae555b0f8b11396364abf6ec500a734e51d",
          "sha1": "7bb16f029b16f4defcdcf78c54395a52352b8eff",
          "md5": "e3fbb34a402d1a9a018a70cb2ead8bdb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModAccessor-1.0.0-javadoc.jar",
          "url": "ModAccessor-1.0.0-javadoc.jar",
          "size": 82294,
          "sha512": "c572e0a5a5d9a22dddec696cdd1ed4027bafacb9c35be889daeb3edc5fe11a3e281aaeb1cc1833172c25177c32538bba741689326fe41be610cf657eee4be6eb",
          "sha256": "07fab49570e3e6439635928e8dcbd8aa5a398b94bd1275e8c1abef47e769460d",
          "sha1": "3cc5caddb805b343535d392e5ccb461a51f6d318",
          "md5": "a9681fcafe81e5162c0b94fd7c66651b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModAccessor-1.0.0-sources.jar",
          "url": "ModAccessor-1.0.0-sources.jar",
          "size": 4253,
          "sha512": "1befe5df640947719096c418f624c8f86ffdf9d120dd9eda03ee6860fc3980daa4c29bf7dd545fbf684eb8bb4e69b3b8bc8dfbcd6f35d37aab38a7803be21fa5",
          "sha256": "aa4fb27f485679321df9e77db9fa26615c0f1c2738e6bb9baa3960ca5cebe278",
          "sha1": "f7a0db46f079140897c11c7b5fb91cb6b3589fdb",
          "md5": "b171c7635ced36a2e20ecb72772d7ca4"
        }
      ]
    }
  ]
}
